import { Deal, Contact, Company, Activity, FollowUpItem } from './crm-types'

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Chalupa U lesa',
    type: 'Hospitality',
    contact: 'Petra Frajmanová',
    email: 'petra@chalupaulesa.cz',
    deals: 2,
    value: '45 000 Kč',
    status: 'Active',
    color: 'blue',
  },
  {
    id: 'comp-2',
    name: 'Studio Kraj s.r.o.',
    type: 'Architecture',
    contact: 'Martin Kraj',
    email: 'martin@studiokraj.cz',
    deals: 2,
    value: '64 000 Kč',
    status: 'Active',
    color: 'violet',
  },
  {
    id: 'comp-3',
    name: 'Novák Architecture',
    type: 'Architecture',
    contact: 'Jan Novák',
    email: 'jan@novakarch.cz',
    deals: 1,
    value: '26 000 Kč',
    status: 'Prospect',
    color: 'amber',
  },
  {
    id: 'comp-4',
    name: 'Mareš & Co.',
    type: 'Consulting',
    contact: 'Lucie Marešová',
    email: 'lucie@maresco.cz',
    deals: 2,
    value: '52 000 Kč',
    status: 'Active',
    color: 'green',
  },
  {
    id: 'comp-5',
    name: 'Forma Studio',
    type: 'Design',
    contact: 'David Formánek',
    email: 'david@formastudio.cz',
    deals: 1,
    value: '18 000 Kč',
    status: 'Prospect',
    color: 'blue',
  },
  {
    id: 'comp-6',
    name: 'Kovář Digital',
    type: 'Technology',
    contact: 'Anna Kovářová',
    email: 'anna@kovardigital.cz',
    deals: 1,
    value: '35 000 Kč',
    status: 'Inactive',
    color: 'violet',
  },
]

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    name: 'Petra Frajmanová',
    role: 'Founder',
    company: 'Chalupa U lesa',
    email: 'petra@chalupaulesa.cz',
    phone: '+420 721 890 123',
    deals: 2,
    lastTouch: 'Today',
    color: 'blue',
  },
  {
    id: 'cont-2',
    name: 'Martin Kraj',
    role: 'Creative director',
    company: 'Studio Kraj s.r.o.',
    email: 'martin@studiokraj.cz',
    phone: '+420 608 432 987',
    deals: 2,
    lastTouch: 'Yesterday',
    color: 'violet',
  },
  {
    id: 'cont-3',
    name: 'Jan Novák',
    role: 'Principal Architect',
    company: 'Novák Architecture',
    email: 'jan@novakarch.cz',
    phone: '+420 777 654 321',
    deals: 1,
    lastTouch: 'Sep 19',
    color: 'amber',
  },
  {
    id: 'cont-4',
    name: 'Lucie Marešová',
    role: 'Managing Partner',
    company: 'Mareš & Co.',
    email: 'lucie@maresco.cz',
    phone: '+420 732 112 456',
    deals: 2,
    lastTouch: 'Sep 18',
    color: 'green',
  },
  {
    id: 'cont-5',
    name: 'David Formánek',
    role: 'Design Lead',
    company: 'Forma Studio',
    email: 'david@formastudio.cz',
    phone: '+420 602 334 556',
    deals: 1,
    lastTouch: 'Sep 15',
    color: 'blue',
  },
  {
    id: 'cont-6',
    name: 'Anna Kovářová',
    role: 'Product Manager',
    company: 'Kovář Digital',
    email: 'anna@kovardigital.cz',
    phone: '+420 723 998 776',
    deals: 1,
    lastTouch: 'Sep 12',
    color: 'violet',
  },
]

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-1',
    title: 'Website redesign & booking flow',
    company: 'Chalupa U lesa',
    value: '15 000 Kč',
    rawAmount: 15000,
    stage: 'Quote sent',
    probability: '80%',
    next: 'Follow up on proposal',
    nextDueDate: 'Today, 10:00',
    color: 'blue',
    contactName: 'Petra Frajmanová',
    contactEmail: 'petra@chalupaulesa.cz',
    notes: 'Client loved the minimal booking concept. Quote sent with 50% deposit terms. Follow up to confirm timeline.',
    startDate: '2026-09-22',
    endDate: '2026-10-15',
    deliverables: [
      { id: 'del-1-1', title: 'Booking flow wireframes & responsive UX', status: 'Done', clientSignOff: true, dueDate: '2026-09-20' },
      { id: 'del-1-2', title: 'High-fidelity Figma presentation', status: 'In Progress', clientSignOff: false, dueDate: '2026-09-24' },
      { id: 'del-1-3', title: 'Next.js frontend build & CMS connection', status: 'Pending', clientSignOff: false, dueDate: '2026-10-05' },
      { id: 'del-1-4', title: 'Vercel deployment & custom domain handoff', status: 'Pending', clientSignOff: false, dueDate: '2026-10-15' },
    ],
    invoices: [
      { id: 'inv-1-1', type: 'Deposit', label: '50% Initial Deposit', amount: 7500, formattedAmount: '7 500 Kč', percentage: 50, status: 'Sent', dueDate: '2026-09-24' },
      { id: 'inv-1-2', type: 'Final', label: '50% Final Delivery Balance', amount: 7500, formattedAmount: '7 500 Kč', percentage: 50, status: 'Draft', dueDate: '2026-10-15' },
    ],
  },
  {
    id: 'deal-2',
    title: 'Brand identity & portfolio',
    company: 'Studio Kraj s.r.o.',
    value: '32 000 Kč',
    rawAmount: 32000,
    stage: 'Negotiation',
    probability: '70%',
    next: 'Send revised scope',
    nextDueDate: 'Today, 14:30',
    color: 'violet',
    contactName: 'Martin Kraj',
    contactEmail: 'martin@studiokraj.cz',
    notes: 'Discussed scope adjustments: CMS setup + custom case study layouts. Prepare revised milestone schedule.',
    startDate: '2026-09-22',
    endDate: '2026-10-30',
    deliverables: [
      { id: 'del-2-1', title: 'Brand identity guidelines & typography system', status: 'Done', clientSignOff: true, dueDate: '2026-09-18' },
      { id: 'del-2-2', title: 'Portfolio architecture & layout design', status: 'In Progress', clientSignOff: false, dueDate: '2026-09-25' },
      { id: 'del-2-3', title: 'CMS integration for case studies', status: 'Pending', clientSignOff: false, dueDate: '2026-10-12' },
      { id: 'del-2-4', title: 'Production release & asset handoff', status: 'Pending', clientSignOff: false, dueDate: '2026-10-30' },
    ],
    invoices: [
      { id: 'inv-2-1', type: 'Deposit', label: '50% Kickoff Deposit', amount: 16000, formattedAmount: '16 000 Kč', percentage: 50, status: 'Sent', dueDate: '2026-09-25' },
      { id: 'inv-2-2', type: 'Final', label: '50% Final Balance', amount: 16000, formattedAmount: '16 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-10-30' },
    ],
  },
  {
    id: 'deal-3',
    title: 'Architecture portfolio site',
    company: 'Novák Architecture',
    value: '26 000 Kč',
    rawAmount: 26000,
    stage: 'Qualified',
    probability: '45%',
    next: 'Prepare discovery call',
    nextDueDate: 'Tomorrow, 09:00',
    color: 'amber',
    contactName: 'Jan Novák',
    contactEmail: 'jan@novakarch.cz',
    notes: 'Initial outreach received. High-end modern projects. Needs mobile-first showcase.',
    startDate: '2026-09-23',
    endDate: '2026-11-10',
    deliverables: [
      { id: 'del-3-1', title: 'Discovery & architectural photo curation', status: 'In Progress', clientSignOff: false, dueDate: '2026-09-23' },
      { id: 'del-3-2', title: 'Editorial portfolio interactive prototype', status: 'Pending', clientSignOff: false, dueDate: '2026-10-08' },
      { id: 'del-3-3', title: 'Static Next.js site build with fast gallery loads', status: 'Pending', clientSignOff: false, dueDate: '2026-11-01' },
    ],
    invoices: [
      { id: 'inv-3-1', type: 'Deposit', label: '50% Project Deposit', amount: 13000, formattedAmount: '13 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-09-28' },
      { id: 'inv-3-2', type: 'Final', label: '50% Completion Payment', amount: 13000, formattedAmount: '13 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-11-10' },
    ],
  },
  {
    id: 'deal-4',
    title: 'Consulting client portal design',
    company: 'Mareš & Co.',
    value: '45 000 Kč',
    rawAmount: 45000,
    stage: 'Scope',
    probability: '60%',
    next: 'Draft wireframes & milestones',
    nextDueDate: 'Thu, Sep 24',
    color: 'green',
    contactName: 'Lucie Marešová',
    contactEmail: 'lucie@maresco.cz',
    notes: 'Scoping meeting complete. Client wants 3 phases: Discovery, UI prototyping, and Tailwind handoff.',
    startDate: '2026-09-24',
    endDate: '2026-11-20',
    deliverables: [
      { id: 'del-4-1', title: 'Scoping specification & technical requirements', status: 'Done', clientSignOff: true, dueDate: '2026-09-21' },
      { id: 'del-4-2', title: 'Client portal wireframes & user flows', status: 'In Progress', clientSignOff: false, dueDate: '2026-09-24' },
      { id: 'del-4-3', title: 'Figma UI design system (desktop & tablet)', status: 'Pending', clientSignOff: false, dueDate: '2026-10-18' },
      { id: 'del-4-4', title: 'Tailwind CSS component kit handoff', status: 'Pending', clientSignOff: false, dueDate: '2026-11-20' },
    ],
    invoices: [
      { id: 'inv-4-1', type: 'Deposit', label: '40% Phase 1 Deposit', amount: 18000, formattedAmount: '18 000 Kč', percentage: 40, status: 'Sent', dueDate: '2026-09-25' },
      { id: 'inv-4-2', type: 'Progress', label: '30% Milestone 2 Delivery', amount: 13500, formattedAmount: '13 500 Kč', percentage: 30, status: 'Draft', dueDate: '2026-10-20' },
      { id: 'inv-4-3', type: 'Final', label: '30% Final Code Delivery', amount: 13500, formattedAmount: '13 500 Kč', percentage: 30, status: 'Draft', dueDate: '2026-11-20' },
    ],
  },
  {
    id: 'deal-5',
    title: 'Visual Identity & Design System',
    company: 'Forma Studio',
    value: '18 000 Kč',
    rawAmount: 18000,
    stage: 'Lead',
    probability: '30%',
    next: 'Schedule 20-min intro sync',
    nextDueDate: 'Fri, Sep 25',
    color: 'blue',
    contactName: 'David Formánek',
    contactEmail: 'david@formastudio.cz',
    notes: 'Referred by Petra. Looking for typography system and Figma token library.',
    startDate: '2026-09-25',
    endDate: '2026-10-25',
    deliverables: [
      { id: 'del-5-1', title: 'Design system scope alignment call', status: 'Pending', clientSignOff: false, dueDate: '2026-09-25' },
      { id: 'del-5-2', title: 'Typography & color tokens Figma file', status: 'Pending', clientSignOff: false, dueDate: '2026-10-10' },
    ],
    invoices: [
      { id: 'inv-5-1', type: 'Deposit', label: '50% Initial Deposit', amount: 9000, formattedAmount: '9 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-09-28' },
      { id: 'inv-5-2', type: 'Final', label: '50% Balance on Delivery', amount: 9000, formattedAmount: '9 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-10-25' },
    ],
  },
  {
    id: 'deal-6',
    title: 'Next.js Web App Prototype',
    company: 'Kovář Digital',
    value: '35 000 Kč',
    rawAmount: 35000,
    stage: 'Quote sent',
    probability: '75%',
    next: 'Await contract sign-off',
    nextDueDate: 'Mon, Sep 28',
    color: 'violet',
    contactName: 'Anna Kovářová',
    contactEmail: 'anna@kovardigital.cz',
    notes: 'Final contract submitted. Deposit invoice drafted.',
    startDate: '2026-09-28',
    endDate: '2026-11-05',
    deliverables: [
      { id: 'del-6-1', title: 'Next.js App Router boilerplate & architecture', status: 'In Progress', clientSignOff: false, dueDate: '2026-09-28' },
      { id: 'del-6-2', title: 'Core prototype interactive workflows', status: 'Pending', clientSignOff: false, dueDate: '2026-10-15' },
    ],
    invoices: [
      { id: 'inv-6-1', type: 'Deposit', label: '50% Kickoff Deposit', amount: 17500, formattedAmount: '17 500 Kč', percentage: 50, status: 'Sent', dueDate: '2026-09-28' },
      { id: 'inv-6-2', type: 'Final', label: '50% Final Handoff', amount: 17500, formattedAmount: '17 500 Kč', percentage: 50, status: 'Draft', dueDate: '2026-11-05' },
    ],
  },
  {
    id: 'deal-7',
    title: 'Corporate Rebrand Sprint',
    company: 'Mareš & Co.',
    value: '28 000 Kč',
    rawAmount: 28000,
    stage: 'Won',
    probability: '100%',
    next: 'Kickoff milestone delivery',
    nextDueDate: 'Done',
    color: 'green',
    contactName: 'Lucie Marešová',
    contactEmail: 'lucie@maresco.cz',
    notes: 'Deposit paid! First sprint begins next Monday.',
    startDate: '2026-09-15',
    endDate: '2026-10-10',
    deliverables: [
      { id: 'del-7-1', title: 'Brand exploration & visual benchmarks', status: 'Done', clientSignOff: true, dueDate: '2026-09-18' },
      { id: 'del-7-2', title: 'New logo vectors & usage guidelines', status: 'In Progress', clientSignOff: true, dueDate: '2026-09-28' },
      { id: 'del-7-3', title: 'Business cards & stationery template export', status: 'Pending', clientSignOff: false, dueDate: '2026-10-10' },
    ],
    invoices: [
      { id: 'inv-7-1', type: 'Deposit', label: '50% Initial Deposit', amount: 14000, formattedAmount: '14 000 Kč', percentage: 50, status: 'Paid', dueDate: '2026-09-15', paidAt: '2026-09-16' },
      { id: 'inv-7-2', type: 'Final', label: '50% Delivery Payment', amount: 14000, formattedAmount: '14 000 Kč', percentage: 50, status: 'Draft', dueDate: '2026-10-10' },
    ],
  },
]

export const INITIAL_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fu-1',
    day: 'Today',
    company: 'Chalupa U lesa',
    action: 'Follow up on quote',
    time: '10:00',
    tone: 'urgent',
    completed: false,
  },
  {
    id: 'fu-2',
    day: 'Today',
    company: 'Studio Kraj',
    action: 'Send revised scope',
    time: '14:30',
    tone: 'urgent',
    completed: false,
  },
  {
    id: 'fu-3',
    day: 'Tomorrow',
    company: 'Novák Architecture',
    action: 'Prepare discovery call',
    time: '09:00',
    tone: 'normal',
    completed: false,
  },
  {
    id: 'fu-4',
    day: 'This week',
    company: 'Mareš & Co.',
    action: 'Share case studies',
    time: 'Fri',
    tone: 'normal',
    completed: false,
  },
]

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    dealId: 'deal-1',
    type: 'Follow-up',
    title: 'Follow up on quote & deposit terms',
    person: 'Petra Frajmanová',
    company: 'Chalupa U lesa',
    date: 'Today, 10:00',
    status: 'Due today',
    color: 'blue',
    summary: `### 📞 Client Call — Sep 22
- **Attendees:** Petra Frajmanová, Oliver Seidl
- **Key Takeaways:**
  • Client loved minimal booking flow prototype.
  • Discussed 50% deposit terms (7 500 Kč).
- **Agreed Decisions:**
  • Oliver to send confirmation email with staging link.`,
  },
  {
    id: 'act-1b',
    dealId: 'deal-1',
    type: 'Call',
    title: 'Initial Discovery Call',
    person: 'Petra Frajmanová',
    company: 'Chalupa U lesa',
    date: 'Sep 18, 14:00',
    status: 'Completed',
    color: 'blue',
    summary: `### 📞 Discovery Session — Sep 18
- **Goal:** Understand booking bottlenecks on current WordPress site.
- **Key Needs:**
  • Direct reservations without high Airbnb commission.
  • Clean mobile-first design tailored to mountain guests.
  • Fast page load under 1.5s on mobile.`,
  },
  {
    id: 'act-2',
    dealId: 'deal-2',
    type: 'Meeting',
    title: 'Scope Alignment & CMS Review',
    person: 'Martin Kraj',
    company: 'Studio Kraj s.r.o.',
    date: 'Today, 14:30',
    status: 'Due today',
    color: 'violet',
    summary: `### 📋 Scope Review Meeting
- **Attendees:** Martin Kraj, Oliver Seidl
- **Deliverables Reviewed:**
  - [x] Brand typography system & color palette
  - [ ] Case study CMS schema
  - [ ] Production Next.js release
- **Budget Adjustments:** Added 7 000 Kč for custom case study animations.`,
  },
  {
    id: 'act-2b',
    dealId: 'deal-2',
    type: 'Call',
    title: 'Brand Strategy Kickoff',
    person: 'Martin Kraj',
    company: 'Studio Kraj s.r.o.',
    date: 'Sep 16, 11:00',
    status: 'Completed',
    color: 'violet',
    summary: `### 🤝 Kickoff Sync
- Agreed on editorial, architectural feel with high typography contrast.
- Approved initial moodboards and benchmark references.`,
  },
  {
    id: 'act-3',
    dealId: 'deal-3',
    type: 'Meeting',
    title: 'Discovery & Photo Curation',
    person: 'Jan Novák',
    company: 'Novák Architecture',
    date: 'Tomorrow, 09:00',
    status: 'Upcoming',
    color: 'amber',
    summary: 'Review 12 featured architecture projects and select high-res assets for hero gallery.',
  },
  {
    id: 'act-4',
    dealId: 'deal-4',
    type: 'Note',
    title: 'Client Portal Scoping Spec',
    person: 'Lucie Marešová',
    company: 'Mareš & Co.',
    date: 'Friday, 16:00',
    status: 'Upcoming',
    color: 'green',
    summary: 'Spec complete. 3 milestone deliveries: Discovery wireframes, UI prototyping, and Tailwind code handoff.',
  },
  {
    id: 'act-5',
    dealId: 'deal-5',
    type: 'Call',
    title: 'Introductory Design System Sync',
    person: 'David Formánek',
    company: 'Forma Studio',
    date: 'Sep 19, 11:00',
    status: 'Completed',
    color: 'blue',
    summary: 'Aligned on brand design needs and design system tokens in Figma.',
  },
]
