import { Deal, Contact, Company, Activity, FollowUpItem } from './crm-types'

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Chalupa U lesa',
    type: 'Hospitality',
    contact: 'Petra Frajmanová',
    email: 'petra@chalupaulesa.cz',
    deals: 2,
    value: '45 000 Kč',
    status: 'Active',
    color: 'blue',
  },
  {
    id: 'comp-2',
    name: 'Studio Kraj s.r.o.',
    type: 'Architecture',
    contact: 'Martin Kraj',
    email: 'martin@studiokraj.cz',
    deals: 2,
    value: '64 000 Kč',
    status: 'Active',
    color: 'violet',
  },
  {
    id: 'comp-3',
    name: 'Novák Architecture',
    type: 'Architecture',
    contact: 'Jan Novák',
    email: 'jan@novakarch.cz',
    deals: 1,
    value: '26 000 Kč',
    status: 'Prospect',
    color: 'amber',
  },
  {
    id: 'comp-4',
    name: 'Mareš & Co.',
    type: 'Consulting',
    contact: 'Lucie Marešová',
    email: 'lucie@maresco.cz',
    deals: 2,
    value: '52 000 Kč',
    status: 'Active',
    color: 'green',
  },
  {
    id: 'comp-5',
    name: 'Forma Studio',
    type: 'Design',
    contact: 'David Formánek',
    email: 'david@formastudio.cz',
    deals: 1,
    value: '18 000 Kč',
    status: 'Prospect',
    color: 'blue',
  },
  {
    id: 'comp-6',
    name: 'Kovář Digital',
    type: 'Technology',
    contact: 'Anna Kovářová',
    email: 'anna@kovardigital.cz',
    deals: 1,
    value: '35 000 Kč',
    status: 'Inactive',
    color: 'violet',
  },
]

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    name: 'Petra Frajmanová',
    role: 'Founder',
    company: 'Chalupa U lesa',
    email: 'petra@chalupaulesa.cz',
    phone: '+420 721 890 123',
    deals: 2,
    lastTouch: 'Today',
    color: 'blue',
  },
  {
    id: 'cont-2',
    name: 'Martin Kraj',
    role: 'Creative director',
    company: 'Studio Kraj s.r.o.',
    email: 'martin@studiokraj.cz',
    phone: '+420 608 432 987',
    deals: 2,
    lastTouch: 'Yesterday',
    color: 'violet',
  },
  {
    id: 'cont-3',
    name: 'Jan Novák',
    role: 'Principal Architect',
    company: 'Novák Architecture',
    email: 'jan@novakarch.cz',
    phone: '+420 777 654 321',
    deals: 1,
    lastTouch: 'Sep 19',
    color: 'amber',
  },
  {
    id: 'cont-4',
    name: 'Lucie Marešová',
    role: 'Managing Partner',
    company: 'Mareš & Co.',
    email: 'lucie@maresco.cz',
    phone: '+420 732 112 456',
    deals: 2,
    lastTouch: 'Sep 18',
    color: 'green',
  },
  {
    id: 'cont-5',
    name: 'David Formánek',
    role: 'Design Lead',
    company: 'Forma Studio',
    email: 'david@formastudio.cz',
    phone: '+420 602 334 556',
    deals: 1,
    lastTouch: 'Sep 15',
    color: 'blue',
  },
  {
    id: 'cont-6',
    name: 'Anna Kovářová',
    role: 'Product Manager',
    company: 'Kovář Digital',
    email: 'anna@kovardigital.cz',
    phone: '+420 723 998 776',
    deals: 1,
    lastTouch: 'Sep 12',
    color: 'violet',
  },
]

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-1',
    title: 'Website redesign & booking flow',
    company: 'Chalupa U lesa',
    value: '15 000 Kč',
    rawAmount: 15000,
    stage: 'Quote sent',
    probability: '80%',
    next: 'Follow up on proposal',
    nextDueDate: 'Today, 10:00',
    color: 'blue',
    contactName: 'Petra Frajmanová',
    contactEmail: 'petra@chalupaulesa.cz',
    notes: 'Client loved the minimal booking concept. Quote sent with 50% deposit terms. Follow up to confirm timeline.',
  },
  {
    id: 'deal-2',
    title: 'Brand identity & portfolio',
    company: 'Studio Kraj s.r.o.',
    value: '32 000 Kč',
    rawAmount: 32000,
    stage: 'Negotiation',
    probability: '70%',
    next: 'Send revised scope',
    nextDueDate: 'Today, 14:30',
    color: 'violet',
    contactName: 'Martin Kraj',
    contactEmail: 'martin@studiokraj.cz',
    notes: 'Discussed scope adjustments: CMS setup + custom case study layouts. Prepare revised milestone schedule.',
  },
  {
    id: 'deal-3',
    title: 'Architecture portfolio site',
    company: 'Novák Architecture',
    value: '26 000 Kč',
    rawAmount: 26000,
    stage: 'Qualified',
    probability: '45%',
    next: 'Prepare discovery call',
    nextDueDate: 'Tomorrow, 09:00',
    color: 'amber',
    contactName: 'Jan Novák',
    contactEmail: 'jan@novakarch.cz',
    notes: 'Initial outreach received. High-end modern projects. Needs mobile-first showcase.',
  },
  {
    id: 'deal-4',
    title: 'Consulting client portal design',
    company: 'Mareš & Co.',
    value: '45 000 Kč',
    rawAmount: 45000,
    stage: 'Scope',
    probability: '60%',
    next: 'Draft wireframes & milestones',
    nextDueDate: 'Thu, Sep 25',
    color: 'green',
    contactName: 'Lucie Marešová',
    contactEmail: 'lucie@maresco.cz',
    notes: 'Scoping meeting complete. Client wants 3 phases: Discovery, UI prototyping, and Tailwind handoff.',
  },
  {
    id: 'deal-5',
    title: 'Visual Identity & Design System',
    company: 'Forma Studio',
    value: '18 000 Kč',
    rawAmount: 18000,
    stage: 'Lead',
    probability: '30%',
    next: 'Schedule 20-min intro sync',
    nextDueDate: 'Fri, Sep 26',
    color: 'blue',
    contactName: 'David Formánek',
    contactEmail: 'david@formastudio.cz',
    notes: 'Referred by Petra. Looking for typography system and Figma token library.',
  },
  {
    id: 'deal-6',
    title: 'Next.js Web App Prototype',
    company: 'Kovář Digital',
    value: '35 000 Kč',
    rawAmount: 35000,
    stage: 'Quote sent',
    probability: '75%',
    next: 'Await contract sign-off',
    nextDueDate: 'Mon, Sep 29',
    color: 'violet',
    contactName: 'Anna Kovářová',
    contactEmail: 'anna@kovardigital.cz',
    notes: 'Final contract submitted. Deposit invoice drafted.',
  },
  {
    id: 'deal-7',
    title: 'Corporate Rebrand Sprint',
    company: 'Mareš & Co.',
    value: '28 000 Kč',
    rawAmount: 28000,
    stage: 'Won',
    probability: '100%',
    next: 'Kickoff milestone delivery',
    nextDueDate: 'Done',
    color: 'green',
    contactName: 'Lucie Marešová',
    contactEmail: 'lucie@maresco.cz',
    notes: 'Deposit paid! First sprint begins next Monday.',
  },
]

export const INITIAL_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fu-1',
    day: 'Today',
    company: 'Chalupa U lesa',
    action: 'Follow up on quote',
    time: '10:00',
    tone: 'urgent',
    completed: false,
  },
  {
    id: 'fu-2',
    day: 'Today',
    company: 'Studio Kraj',
    action: 'Send revised scope',
    time: '14:30',
    tone: 'urgent',
    completed: false,
  },
  {
    id: 'fu-3',
    day: 'Tomorrow',
    company: 'Novák Architecture',
    action: 'Prepare discovery call',
    time: '09:00',
    tone: 'normal',
    completed: false,
  },
  {
    id: 'fu-4',
    day: 'This week',
    company: 'Mareš & Co.',
    action: 'Share case studies',
    time: 'Fri',
    tone: 'normal',
    completed: false,
  },
]

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'Follow-up',
    title: 'Follow up on quote',
    person: 'Petra Frajmanová',
    company: 'Chalupa U lesa',
    date: 'Today, 10:00',
    status: 'Due today',
    color: 'blue',
    summary: 'Check if Petra reviewed the booking flow proposal and deposit breakdown.',
  },
  {
    id: 'act-2',
    type: 'Email',
    title: 'Send revised scope',
    person: 'Martin Kraj',
    company: 'Studio Kraj s.r.o.',
    date: 'Today, 14:30',
    status: 'Due today',
    color: 'violet',
    summary: 'Email updated scope document including CMS integration and 2 review rounds.',
  },
  {
    id: 'act-3',
    type: 'Meeting',
    title: 'Prepare discovery call',
    person: 'Jan Novák',
    company: 'Novák Architecture',
    date: 'Tomorrow, 09:00',
    status: 'Upcoming',
    color: 'amber',
    summary: '30-minute Google Meet to review portfolio aesthetic requirements.',
  },
  {
    id: 'act-4',
    type: 'Note',
    title: 'Share case studies',
    person: 'Lucie Marešová',
    company: 'Mareš & Co.',
    date: 'Friday, 16:00',
    status: 'Upcoming',
    color: 'green',
    summary: 'Send PDF portfolio of previous B2B portal implementations.',
  },
  {
    id: 'act-5',
    type: 'Call',
    title: 'Introductory call',
    person: 'David Formánek',
    company: 'Forma Studio',
    date: 'Sep 19, 11:00',
    status: 'Completed',
    color: 'blue',
    summary: 'Aligned on brand design needs and design system tokens.',
  },
]
